### ISSUE TITLE
Metalness

### ISSUE THREAD

**Issue by Popperelay** [selfshadow/ltc_code#2]
Hello. If we use LTCs method to calculate BRDF integral, how to reflect the influence of metalness on the integral results? It seems that the factor of metalness is not taken into account when fitting matrix M. Thanks!

**Comment by selfshadow** [comment]
If you take a look at any of the WebGL demos, you will see that they work with diffuse and specular colours (dcol and scol, respectively). You can therefore convert your "base colour" and metalness values to these terms -- in the standard way -- then proceed from there.

NB: we don't include Fresnel in the fitting of specular lobes, but instead approximate it using a separate integral. (See the "LTC Fresnel Approximation” note on the [project page](https://blog.selfshadow.com/publications/s2016-advances/) for more details.)

I hope that explains things!

**Comment by Popperelay** [comment]
Oh, I see! Thank you so much!
