### ISSUE TITLE
Light source below the ground

### ISSUE THREAD

**Issue by XINWUYA** [selfshadow/ltc_code#3]
Hello, may I ask you a question? If there is only one light source and one horizontal plane in the scene, and the light source is below the horizontal plane, is it possible that some of the light source will be above the horizontal plane after multiplying the LTC matrix M ？If so, the horizontal plane will be illuminated. Do I need to tailor the polygonal light source before multiplying matrix M?

**Comment by selfshadow** [comment]
It's possible for the LTC lobe to produce light on the opposite side for certain configurations of view angle and roughness. There are a few potential fixes for this:

- Constrain the fitting so this can't happen. I suspect this will have a negative impact on overall accuracy.
- Clip the light to the surface horizon before the transform (I believe this is what you're suggesting). This is also undesirable as it will require evaluating more edges later, along with a more general edge clipping loop that can handle N edges. There is code for this in our original reference code (see the paper's [project page](https://eheitzresearch.wordpress.com/415-2/)), but it's going to be slower than the optimised quad version.
- Introduce some additional term that prevents light leaking. I'm not sure if this is possible, but it's something I may look into in the future.

I hope that answers your question! I should also mention that I haven't seen visual artefacts from this problem in production, but it can prevent some light culling opportunities.

**Comment by XINWUYA** [comment]
Thank you so much! And I have another doubt: it seems that the greater the roughness, the greater the error of the fit between LTC and BRDF. What could be the cause？

**Comment by XINWUYA** [comment]
Thank you so much! So is it true that this may happen: the light source is originally above the tangent plane, but after multiplying the matrix, all of it becomes below the plane?  And I have another doubt: it seems that the greater the roughness, the greater the error of the fit between LTC and BRDF. What could be the cause？

**Comment by XINWUYA** [comment]
Thank you so much! So is it true that this may happen: the light source is originally above the tangent plane, but after multiplying the matrix, all of it becomes below the plane for certain configurations of view angle and roughness? And I have another doubt: it seems that the greater the roughness, the greater the error of the fit between LTC and BRDF. What could be the cause？

**Comment by selfshadow** [comment]
> but after multiplying the matrix, all of it becomes below the plane for certain configurations of view angle and roughness?

Yes, this can happen, but it's not necessarily an error. For instance, at low roughness, the lobe will be highly directional and will only 'intersect' the light near the reflection direction -- in other cases, the transformed light will fall below the plane (== no light).

If you have further questions like this, I would recommend verifying for yourself in order to gain intuition.

> And I have another doubt: it seems that the greater the roughness, the greater the error of the fit between LTC and BRDF. What could be the cause？

This depends on the particular BRDF you've fitted. For GGX, we have comparison plots in the supplemental.
