### ISSUE TITLE
Darker at grazing angle compared to groundtruth

### ISSUE THREAD

**Issue by ElaraFX** [selfshadow/ltc_code#5]
Hi,

I tried this code with a diffuse only surface and an area light at grazing angle, the result is much darker compared to Monte Carlo groundtruth.

I understand this method is an approximation, but is there a way to improve its accuracy at grazing angle?

**Comment by selfshadow** [comment]
The method should be almost exact for a quad light when not using the "clipless approximation". Could you share any more details about your implementation (is it directly based on the latest code in depot?) and the scene configuration you're using (the area light type, dimensions and angle relative to the receiver, etc.)? Some screenshots showing this issue would be ideal.

Thanks!

**Comment by ElaraFX** [comment]
[AnalyticLightBug.zip](https://github.com/selfshadow/ltc_code/files/3454706/AnalyticLightBug.zip)

Hi, @selfshadow 

The real scene is too complex, so I take some time to reproduce the issue with a simpler scene.

I attached image comparison, Maya scene, and screenshot of the scene configuration in the ZIP file here.

Hope this is clear.

**Comment by ElaraFX** [comment]
@selfshadow 

Sorry, this looks like my own issue. After disabling my own shadow code, the approximation works perfectly.

**Comment by selfshadow** [comment]
Okay, no problem! I appreciate you taking the time to report this, even if it's turned out not to be a bug.
