### ISSUE TITLE
Texture Prefilter Tool is giving incorrect results

### ISSUE THREAD

**Issue by gamehacker1999** [selfshadow/ltc_code#7]
So I created a new C++ project and copied the texture prefilter tool code to it. I also grabbed the CImg.h and the required stb headers to run it. However when I try to prefilter a texture, the resulting textures have incorrect colors, I am not quite sure what is causing this[](url)

**Comment by selfshadow** [comment]
I think the issue you're running into is that the output texture from the prefiltering tool is rgb9e5 encoded:
https://github.com/selfshadow/ltc_code/blob/texture/prefilter/prefilterAreaLight.cpp#L254

I opted for this format for the WebGL demo as there was limited support for HDR image formats. You can of course modify your copy of the code.
